stages:
- build
- style
- test
- deploy
- notify

building:
  stage: build
  tags: 
    - build
  script:
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  after_script:
    - bash src/notify.sh build

style_test:
  stage: style
  tags: 
    - style
  script:
    - cp materials/linters/.clang-format .
    - clang-format --version
    - cd src/cat/ 
    - clang-format -n *.c *.h &> clang_out.txt
    - cat clang_out.txt
    - if [ -s clang_out.txt ]; then
        echo "clang-format found formatting issues in src/cat/";
        exit 1;
      fi
    - cd ../grep/
    - clang-format -n *.c *.h &> clang_out.txt
    - cat clang_out.txt
    - if [ -s clang_out.txt ]; then
        echo "clang-format found formatting issues in src/grep/";
        exit 1;
      fi
  after_script:
    - bash src/notify.sh style

testing:
  stage: test
  tags: 
    - test
  script:
  - cd src/
  - bash integrations_tests.sh
  after_script:
    - bash src/notify.sh test

deploying:
  stage: deploy
  tags:
    - deploy
  script:
    - chmod 777 src/deploy.sh
    - bash src/deploy.sh
  when: manual
  after_script:
    - bash src/notify.sh deploy

notification:
  stage: notify
  tags: 
    - notify
  script:
  - cd src/
  - bash src/notify.sh ALL_STAGES_COMPLETE