stages:
- build
- style

building:
  stage: build
  tags: 
    - build
  script:
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

style_test:
  stage: style
  tags: 
    - style
  script:
    - clang-format -i -style=google **/*.c **/*.h
    - git diff --exit-code