stages:
- build
- style

building:
  stage: build
  tags: 
    - build
  script:
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

style_test:
  stage: style
  tags: 
    - style
  script:
    - clang-format --version # вывод версии clang-format для отладки
    - cd src/cat/ 
    - clang-format -n *.c *.h &> clang_out.txt
    - cat clang_out.txt
    - cd ../grep/
    - clang-format -n *.c *.h &> clang_out.txt
    - cat clang_out.txt
    # - |
    #   echo "Checking code style for src/cat directory..."
    #   clang-format -style=Google -output-replacements-xml $(find src/cat -name "*.c" -or -name "*.h") || true
    # - |
    #   echo "Checking code style for src/grep directory..."
    #   clang-format -style=Google -output-replacements-xml $(find src/grep -name "*.c" -or -name "*.h") || true