stages:
- build
- style

build:
  stage: build
  tags: 
    - build
  script:
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

style:
  stage: style
  script:
    - clang-format --version # вывод версии clang-format для отладки
    - cd src/cat/
    - clang-format -style=Google -output-replacements-xml $(find . -name "*.c" -or -name "*.h") > format.xml || true
    - cat format.xml # вывод результата clang-format для отображения в CI
    - |
      if grep -q "offset" format.xml; then
        echo "Code style check failed. Please run clang-format to fix formatting issues."
        exit 1
      else
        echo "Code style check passed."
      fi
    - cd ../grep/
        - clang-format -style=Google -output-replacements-xml $(find . -name "*.c" -or -name "*.h") > format.xml || true
    - cat format.xml # вывод результата clang-format для отображения в CI
    - |
      if grep -q "offset" format.xml; then
        echo "Code style check failed. Please run clang-format to fix formatting issues."
        exit 1
      else
        echo "Code style check passed."
      fi